/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/

import { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import SkyScene from "../../assets/anime_sky.glb";

export default function SkyModel(props) {
  const { nodes, materials } = useGLTF(SkyScene);
  const skyRef = useRef(null);

  useFrame((state, delta) => (skyRef.current.rotation.y -= 0.0009));

  return (
    <a.group {...props} ref={skyRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={50000}
      />
    </a.group>
  );
}
