/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: twicetaze (https://sketchfab.com/twicetaze)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-swamp-ee1d6f8807ea4f48948051413862b268
Title: The Swamp
*/

import { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import SwampScene from "../../assets/the_swamp.glb";

export default function SwampModel(props) {
  const swampRef = useRef(null);
  const { nodes, materials } = useGLTF(SwampScene);

  useFrame((state, delta) => (swampRef.current.rotation.y += 0.002));

  return (
    <a.group ref={swampRef} {...props}>
      <group
        position={[-39.18, 145.924, 72.36]}
        rotation={[0.103, 0.736, -1.625]}
        scale={0.422}
      >
        <mesh
          geometry={nodes.Plane003_Steam_0.geometry}
          material={materials.Steam}
          position={[6.567, -4.31, -5.284]}
          scale={110.505}
        />
      </group>
      <group
        position={[-90.39, 26.984, 227.497]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.127}
      >
        <mesh
          geometry={nodes.Mushroom_Mushroom_0.geometry}
          material={materials.Mushroom}
          position={[1365.156, -928.494, 51.265]}
          scale={1327.248}
        />
      </group>
      <group
        position={[-90.39, 26.984, 170.893]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.127}
      >
        <mesh
          geometry={nodes.Mushroom001_Mushroom_0.geometry}
          material={materials.Mushroom}
          position={[653.695, -452.373, 82.724]}
          scale={1552.395}
        />
      </group>
      <group
        position={[-76.677, 48.381, 191.473]}
        rotation={[0, -0.082, 0]}
        scale={0.809}
      >
        <mesh
          geometry={nodes.Shrek_Trim_0.geometry}
          material={materials.Trim}
          position={[-0.473, 1.046, -0.775]}
          scale={37.966}
        />
      </group>
      <group position={[12.93, -6.505, -25.288]}>
        <mesh
          geometry={nodes.Barrel_Trim_0.geometry}
          material={materials.Trim}
          position={[-0.009, 0.008, -0.013]}
          scale={19.686}
        />
      </group>
      <group
        position={[176.501, 22.932, -14]}
        rotation={[Math.PI / 2, 0, -0.833]}
        scale={0.006}
      >
        <mesh
          geometry={nodes.Cylinder020_Vagon_0.geometry}
          material={materials.Vagon}
          position={[13.96, 0.524, 6.342]}
          scale={2229.665}
        />
      </group>
      <group position={[54.684, -7.346, -15.134]} scale={0.006}>
        <mesh
          geometry={nodes.Cylinder021_Vagon_0.geometry}
          material={materials.Vagon}
          position={[-3.532, 6.875, 20.8]}
          scale={2182.468}
        />
      </group>
      <group
        position={[-32.437, 17.007, 82.551]}
        rotation={[Math.PI / 2, 0, -0.833]}
        scale={0.006}
      >
        <mesh
          geometry={nodes.Vagoon_Vagon_0.geometry}
          material={materials.Vagon}
          position={[-0.022, -17419.838, -12986.308]}
          scale={8657.814}
        />
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon006_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-15.418, 2837.876, -6720.746]}
            scale={3727.501}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon007_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-12.377, 1816.945, -6694.08]}
            scale={3588.664}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon008_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-6.206, 88.969, -6551.579]}
            scale={3650.162}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon009_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0.562, 4932.72, -6957.763]}
            scale={3533.017}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon010_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-10.402, 5290.875, -6996.613]}
            scale={2666.108}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon011_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 6175.463, -5738.904]}
            scale={1371.396}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon012_Vagon_0.geometry}
            material={materials.Vagon}
            position={[638.866, 6241.079, -6962.111]}
            scale={491.687}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon013_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 6336.131, -6091.28]}
            scale={1245.68}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon014_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-2.449, -1781.984, -6328.668]}
            scale={2481.891}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon015_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0.001, -1687.817, -6362.715]}
            scale={3302.178}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon016_Vagon_0.geometry}
            material={materials.Vagon}
            position={[43.916, 498.588, -13265.883]}
            scale={3472.044}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon017_Vagon_0.geometry}
            material={materials.Vagon}
            position={[10.93, -1248.445, -2566.464]}
            scale={5765.671}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon018_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -4702.589, -4857.38]}
            scale={2907.573}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon019_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -4907.075, -11933.148]}
            scale={2923.975}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon020_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -3152.957, -9895.453]}
            scale={2864.043}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon021_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -2435.732, -5956.117]}
            scale={2968.015}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon052_Vagon_0.geometry}
            material={materials.Vagon}
            position={[8.003, -4027.317, -3658.875]}
            scale={2922.703}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon053_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -1345.76, -3492.885]}
            scale={6474.987}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon022_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -4335.266, -10907.493]}
            scale={2767.399}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon023_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 1747.969, -3972.987]}
            scale={2765.944}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon050_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 5030.427, -3934.46]}
            scale={3162.759}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon051_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 5227.356, -3916.092]}
            scale={3003.721}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon054_Vagon_0.geometry}
            material={materials.Vagon}
            position={[772.242, -1957.521, -6834.163]}
            scale={225.193}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon031_Vagon_0.geometry}
            material={materials.Vagon}
            position={[565.562, -1893.335, -6695.409]}
            scale={116.01}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon032_Vagon_0.geometry}
            material={materials.Vagon}
            position={[737.679, -1905.208, -6897.14]}
            scale={601.949}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon055_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-1492.298, -3193.526, -4114.715]}
            scale={679.261}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon033_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-1476.501, -3183.917, -5458.652]}
            scale={1239.511}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon002_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -8337.775, -3560.694]}
            scale={654.942}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon034_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 2847.282, -2630.023]}
            scale={4694.898}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon035_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 2833.797, -3414.824]}
            scale={4558.929}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon036_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 2848.584, -3448.912]}
            scale={4350.49}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon024_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 2934.966, -3452.048]}
            scale={4387.578}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon056_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 3662.098, -3455.768]}
            scale={4581.588}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon057_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 2586.89, -3458.021]}
            scale={5092.152}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon058_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -255.414, -3452.626]}
            scale={4769.721}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon059_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 210.727, -3451.424]}
            scale={5165.039}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon037_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -1337.137, -3450.443]}
            scale={5332.391}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon060_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, 4769.745, -3456.115]}
            scale={5122.63}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon038_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -1336.557, -3604.671]}
            scale={4377.416}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon039_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -1333.887, -3452.102]}
            scale={5457.733}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon040_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -4188.664, -1869.415]}
            scale={4389.502}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon041_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -4171.396, -2133.567]}
            scale={4577.313}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon025_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -4106.196, -2159.062]}
            scale={4442.618}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon061_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -676.842, -1577.468]}
            scale={4486.551}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon062_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -17393.472, -7739.119]}
            scale={7397.966}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon063_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -17436.132, -7767.347]}
            scale={7266.407}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon064_Vagon_0.geometry}
            material={materials.Vagon}
            position={[4.063, -24185.743, -3472.312]}
            scale={3229.845}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon003_Vagon_0.geometry}
            material={materials.Vagon}
            position={[1503.657, -23626.792, -6437.341]}
            scale={327.601}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon065_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -23547.904, -7190.348]}
            scale={3443.651}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon066_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-0.632, -23538.119, -6874.063]}
            scale={3070.211}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon026_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -19003.824, -3517.333]}
            scale={7817.184}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon004_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-3.197, -9688.624, -3940.231]}
            scale={1456.288}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon005_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -11320.548, -3523.127]}
            scale={316.722}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon042_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -15169.724, -1552.591]}
            scale={4396.556}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon043_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -20043.596, -1552.591]}
            scale={4281.37}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon044_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -17596.227, -1767.263]}
            scale={4518.307}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon027_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -17614.238, -1787.819]}
            scale={4388.05}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon045_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-177.769, -26207.837, -5287.282]}
            scale={1440.979}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon046_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -26311.536, -5287.783]}
            scale={1947.78}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon047_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -26810.099, -5272.329]}
            scale={3758.456}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon001_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-22.852, -26899.509, -6699.441]}
            scale={3530.309}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon048_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -25949.823, -3854.766]}
            scale={2074.269}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon049_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-175.858, -25838.954, -3845.968]}
            scale={260.465}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon028_Vagon_0.geometry}
            material={materials.Vagon}
            position={[-12.791, -17449.775, -2571.692]}
            scale={5017.115}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon029_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -27239.363, -6699.441]}
            scale={3827.698}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon030_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -17393.473, -11306.241]}
            scale={8147.342}
          />
        </group>
        <group position={[0.002, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vagoon067_Vagon_0.geometry}
            material={materials.Vagon}
            position={[0, -17616.712, -1481.763]}
            scale={3382.858}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree3_tree_0.geometry}
        material={materials.tree}
        position={[-98.144, 101.197, 268.385]}
        scale={100.573}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree1_tree_0.geometry}
        material={materials.tree}
        position={[-130.844, 153.545, 175.297]}
        scale={136.428}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree2_tree_0.geometry}
        material={materials.tree}
        position={[4.972, 111.104, 267.875]}
        scale={101.548}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree4_tree_0.geometry}
        material={materials.tree}
        position={[-219.577, 116.966, 28.247]}
        scale={107.947}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree6_tree_0.geometry}
        material={materials.tree}
        position={[232.474, 108.13, -60.094]}
        scale={101.548}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree5_tree_0.geometry}
        material={materials.tree}
        position={[-20.799, 142.595, 196.129]}
        scale={130.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock1_Rock_0.geometry}
        material={materials.Rock}
        position={[-164.951, 14.903, 179.483]}
        scale={5.848}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock2_Rock_0.geometry}
        material={materials.Rock}
        position={[-95.199, 25.437, 158.01]}
        scale={15.651}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock3_Rock_0.geometry}
        material={materials.Rock}
        position={[7.803, 17.913, 203.047]}
        scale={7.236}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock4_Rock_0.geometry}
        material={materials.Rock}
        position={[-170.662, 9.029, 51.844]}
        scale={7.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock5_Rock_0.geometry}
        material={materials.Rock}
        position={[33.454, 28.625, 244.757]}
        scale={22.403}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock6_Rock_0.geometry}
        material={materials.Rock}
        position={[214.957, 49.583, 18.686]}
        scale={55.083}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock7_Rock_0.geometry}
        material={materials.Rock}
        position={[65.518, 25.04, 251.748]}
        scale={9.818}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fences_Trim_0.geometry}
        material={materials.Trim}
        position={[31.687, 27.207, 29.362]}
        scale={183.94}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lake_Landscape_0.geometry}
        material={materials.Landscape}
        position={[4.803, -25.094, 27.978]}
        scale={281.656}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landsacpe1_Landscape_0.geometry}
        material={materials.Landscape}
        position={[5.486, -1.87, 72.494]}
        scale={271.268}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lotus_Trim_0.geometry}
        material={materials.Trim}
        position={[27.26, -7.007, -35.857]}
        scale={118.887}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_Trim_0.geometry}
        material={materials.Trim}
        position={[7.284, 21.67, 55.696]}
        scale={213.539}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge_Trim_0.geometry}
        material={materials.Trim}
        position={[-41.846, 5.827, 74.846]}
        scale={109.651}
      />
    </a.group>
  );
}
